#!/bin/sh

wait() {
    until [ $(pidof -s $1) ]
    do 
        sleep 1
    done
}

# Now work, use the '-dpi' of X to solve this
# set resolution and dpi for MacBook Pro 13-inch
# xrandr --output DUMMY0 --mode "2560x1600_60.00" --dpi 227
# xrandr -s 2560x1600 --dpi 227

X :0 -config /etc/xorg-forward/dummy.conf -listen tcp -ac -dpi 227 &
wait Xorg

# xrdb -display :0 -global /etc/xorg-forward/Xresources 
xrdp --config /etc/xorg-forward/xrdp.ini &
x11vnc -display :0 -forever -bg
i3 -c /etc/xorg-forward/i3config




