#!/bin/bash

set -e

## update window name
echo -ne "\033]0; $(hostname) \007"

#ETC_DIR=etc
ETC_DIR=/etc/laborbenko
RETRY=3
ENV=DISPLAY,CCACHE_DIR,http_proxy,https_proxy,BASH_FUNC_clone%%,BASH_FUNC_set-env%%

function run_as {
    local user=$1
    shift;
    runuser -w $ENV -s /bin/bash - "$user" -c "$*"
}

function apt {
    command apt -o Acquire::http::proxy=false \
                -o APT::Install-Recommends=false \
                -o APT::Install-Suggests=false \
                "$@"
}

function load_layer {
    exec_cmds "$1" "$ETC_DIR/$1"
}

function clone {
    local dir="$1"
    local repo="$2"
    rm -rf "$dir"
    git clone --depth 1 "$repo"
    cd "$dir"
    git config remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*'
}

export -f clone

function set-env {
    local user=$1
    local name=$2
    local value="$3"
    export "$name"="$value"
    export ENV="$ENV,$2"
    run_as "$user" "export $name=$value"
    run_as "$user" "echo export $name=$value >> ~/.bashrc"
}

export -f set-env

function clean-tmp {
    apt clean
    apt autoremove --yes
    rm -rf /tmp
    rm -rf /var/lib/apt/lists/*
    find /var | grep '\.log$' | xargs rm -v
}

# automatically retry N times after failure
function with_retry {
    local i=0
    local result=0
    local cmd="$1"
    echo "$cmd"
    while true
    do
        set +e
        eval "$cmd"
        result=$?
        set -e

        [ $result -eq 0 ] && return 0
        [ $i -ge $RETRY ] && echo "Automatic installation failed, enter manual mode" && exec bash

        i=$(( i+1 ))
        local sleep=$(( i * 3))
        printf "Execute failed,retry:%d,sleep:%d\ncommand:%s\n" $i $sleep "$cmd"
        sleep $sleep
    done
}

# recoverable init script
function recoverable_exec_cmds {
    local index=0
    local layer=$1
    shift;
    local cmds=("$@")
    local cursor="$ETC_DIR/cursor_$layer"
    local len=${#cmds[@]}

    ## find the last succeeded index of commands
    if [[ -f $cursor ]]; then
        index=$(( $(cat "$cursor") + 1 ))
    else
        echo -1 > "$cursor"
        chmod 666 "$cursor"
    fi

    # this index must be local or its value will incorrectly be updated by the sub `load_layer` function
    # which is called by the eval and the wrong value will be inherited by the parent function, which leads to this eval loop breaking
    local i=$index
    for (( ; i<len; i++ ))
    do
        local cmd="${cmds[$i]}"
        with_retry "$cmd"
        echo $i > "$cursor"
    done
}

function exec_cmds {
    local layer=$1
    local file=$2
    local cmds=( )

    ## if there is a valid layer, load it
    ## otherwise, treat this script as a login process
    ## and override the IS_BUILD value or the container will immediately exit
    if [ -n "$file" ]; then
        # no readarry in Mac
        while IFS='' read -r line; do
            cmds+=( "$line" )
        done < "$file"
    else
        IS_BUILD=0
        return 0
    fi

    recoverable_exec_cmds "$layer" "${cmds[@]}"
}

while getopts “l:e:b:” argv
do
     case $argv in
         l)
             LAYER=$OPTARG
             ;;
         e)
             EVAL="$OPTARG"
             ;;
         b)
             IS_BUILD=$OPTARG
             ;;
         ?)
         ;;
     esac
done

[ -n "$LAYER" ] && [ "init" != "$LAYER" ] && exec_cmds "$LAYER" "$ETC_DIR/$LAYER"

## eval is always executed at the last for load some customized instructions
if [ -n "$EVAL" ]; then
    echo "eval:$EVAL"
    while read -d ";" -r cmd; do
        with_retry "$cmd"
    done <<< "$EVAL"
fi

if $IS_BUILD; then
    exit 0
fi

[ -x "$(command -v wg)" ] && setup-wg

su -w $ENV -s /bin/bash - firest
