#!/bin/bash

scriptDir=$(dirname -- "$(readlink -f -- "$BASH_SOURCE")")
Dev=utun254
Address="10.254.0.1"
Network="10.254.0.0"
PrivateKey="cNdl/h6EbaeRf4LRk/UPo/jsqPghiFcYEc1hKC65VUs="
ListenPort=50000

function wg-up {
    wireguard-go "$Dev"
    wg set "$Dev" \
       listen-port $ListenPort \
       private-key <(echo "$PrivateKey")
    ifconfig "$Dev" inet "$Address/16" "$Address" alias
    ifconfig "$Dev" up
    route -q -n add -inet "$Network/16" -interface "$Dev"
}

function wg-down {
    rm -f /var/run/wireguard/"$Dev".sock
    route delete -net "$Network/16"
}

wg-up
$scriptDir/bin/dns-svr
#wg-down
